language: c++
compiler:
   - gcc
   - clang

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install python-dev; fi        

before_script:
  - git clone --depth 10 https://github.com/agra-uni-bremen/dependencies.git       
  - ./bootstrap.sh --deps deps --free --model RelWithDebInfo 


script:
  - cd build && make && ctest -j2 --timeout 5 
